version: '2'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8102:3306
    expose:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    links:
      - db
    ports:
      - 8101:8080
  app:
    build:
      context: ./docker/node
    links:
      - db
    ports:
      - 8100:8080
    volumes:
      - ./server:/usr/src/app
