version: '2'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8092:3306
    expose:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8091:8080
  app:
    build:
      context: ./docker/node
    ports:
      - 8090:8080
    volumes:
      - ./server:/usr/src/app
